### ISSUE TITLE
bundle efforts

### ISSUE THREAD

**Issue by yoshuawuyts** [mattdesl/no-op#1]
I'll link to you, if you link to mine :tada::tada::tada::tada::tada::tada::tada::tada::tada:
https://github.com/yoshuawuyts/noop2

**Comment by yoshuawuyts** [comment]
https://github.com/yoshuawuyts/noop2/commit/6b3ee89215e9c4cced28aee1dd37dc9554635966

**Comment by mattdesl** [comment]
:+1: my google fu failed me since I only found [noop](https://www.npmjs.org/package/noop) and [node-noop](https://www.npmjs.org/package/node-noop) which are both pretty weird.

**Comment by mattdesl** [comment]
https://github.com/mattdesl/no-op/commit/e62ffcda2d4d492100e65918636bab1bc3b19ee5

**Comment by yoshuawuyts** [comment]
:D haha, if anything there should be more of these out there!

**Comment by yoshuawuyts** [comment]
`squat.js`: sit down on npm and do nothing.
